[improve-has-focus] Improve the has focus getting rid of third party dependencies
dreipol/scss-utils pull request #3
Opened 2019-02-18 08:04 UTC by GianlucaGuarini

This PR will get rid of the custom `has-support` mixin improving the `has-focus` helper using only pure CSS without relying on modernizr.
This change is a breaking change.

Side note:
According to my tests the `pointer: fine` seems to be supported also by Internet Explorer 11
https://developer.mozilla.org/en-US/docs/Web/CSS/@media/pointer
https://whatwebcando.today/pointer-adaptation.html

2019-02-18 09:07 UTC, nirazul requested changes
We've discussed the PR together. As discussed, I'd be more in favour of a `@media (hover: hover/none)` solution with a ie11 hack that we can remove when our support ends.
Additionally, I'd like to keep the mixin in the list, so that we can still use it when we need it.

2019-02-20 07:33 UTC, nirazul approved these changes

2019-02-20 07:34 UTC, nirazul commented
@GianlucaGuarini I've added media queries to all `@content` outlets, so the specifity is always the same. I've also added a bit of documentation.

If you agree, we can merge this.

2019-03-01 07:56 UTC, faebeee commented
👍 :

2019-03-05 16:18 UTC, merged